### ISSUE TITLE
This is a black and white qr code, but we will not use it in the specific propaganda, so I hope you can tell me how to achieve the color of the qr code, if there is an example that is better, thank you very much

### ISSUE THREAD

**Issue by fenglijunnb** [boombuler/barcode#62] opened 2020-03-24 10:43 UTC
![it399 com qrcode2](https://user-images.githubusercontent.com/48191768/77416790-4fbb8980-6dff-11ea-8a2d-689db1e420c0.jpg)
![image](https://user-images.githubusercontent.com/48191768/77416812-55b16a80-6dff-11ea-9d89-151bd8ebfb82.png)
![image](https://user-images.githubusercontent.com/48191768/77416826-5ba74b80-6dff-11ea-9b37-be94fa71ae5b.png)

**Comment by boombuler** [comment] 2020-03-24 11:14
Duplicate of #61

**Closed by boombuler** 2020-03-24 11:14 UTC
